services:
  webcpp:
    build: .
    ports:
      - "8081:8081"
      - "443:8443"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./ybuestc.art_nginx:/app/ybuestc.art_nginx
    restart: unless-stopped
